# Generated by Django 4.2.28 on 2026-03-03 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='verification',
            new_name='verificatio_status_71f14a_idx',
            old_name='verification_status_9ee794_idx',
        ),
        migrations.RenameIndex(
            model_name='verification',
            new_name='verificatio_user_id_80fff9_idx',
            old_name='verification_user_id_d26b60_idx',
        ),
    ]
