# Generated by Django 4.2.28 on 2026-03-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "verifications",
            "0002_rename_verification_status_9ee794_idx_verificatio_status_71f14a_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="verification",
            name="id_back_url",
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name="verification",
            name="id_front_url",
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name="verification",
            name="selfie_url",
            field=models.URLField(max_length=500),
        ),
    ]
