# Generated by Django 4.2.28 on 2026-03-03 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='offer',
            new_name='offers_is_dele_15d9e5_idx',
            old_name='offers_offer_is_dele_75bfa7_idx',
        ),
        migrations.RenameIndex(
            model_name='offer',
            new_name='offers_is_dele_229b30_idx',
            old_name='offers_offer_is_dele_40ba95_idx',
        ),
        migrations.RenameIndex(
            model_name='redemption',
            new_name='redemptions_user_id_fd100a_idx',
            old_name='redemptions_user_id_79b0ca_idx',
        ),
        migrations.RenameIndex(
            model_name='redemption',
            new_name='redemptions_offer_i_c4f8ff_idx',
            old_name='redemptions_offer_i_5fd582_idx',
        ),
    ]
