# Generated by Django 4.2.28 on 2026-03-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "offers",
            "0002_rename_offers_offer_is_dele_75bfa7_idx_offers_is_dele_15d9e5_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="client_logo_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="offer",
            name="poster_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="offer",
            name="url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
