# Generated by Django 4.2.28 on 2026-03-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0003_alter_offer_client_logo_url_alter_offer_poster_url_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="offer",
            name="offers_is_dele_15d9e5_idx",
        ),
        migrations.RemoveIndex(
            model_name="offer",
            name="offers_is_dele_229b30_idx",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="is_deleted",
        ),
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(
                fields=["status", "-created_at"], name="offers_status_6eedf4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(
                fields=["category", "-created_at"], name="offers_categor_b6b047_idx"
            ),
        ),
    ]
