# Generated by Django 4.2.28 on 2026-03-02 22:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('survey_id', models.CharField(db_index=True, max_length=128)),
                ('survey_title', models.CharField(blank=True, max_length=500)),
                ('user_id', models.CharField(db_index=True, max_length=128)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField()),
                ('answers', models.JSONField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'responses',
                'unique_together': {('user_id', 'survey_id')},
            },
        ),
    ]
