# Generated by Django 4.2.28 on 2026-03-03 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("responses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="response",
            name="is_deleted",
        ),
    ]
