version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: looksharp
      POSTGRES_USER: looksharp_app
      POSTGRES_PASSWORD: looksharpapp123
    ports: ["5432:5432"]
    volumes: [postgres_data:/var/lib/postgresql/data]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes: [.:/app]
    ports: ["8000:8000"]
    env_file: .env
    depends_on: [db, redis]

  worker:
    build: .
    command: celery -A config worker -Q critical,default,bulk -l info
    volumes: [.:/app]
    env_file: .env
    depends_on: [db, redis]

  scheduler:
    build: .
    command: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes: [.:/app]
    env_file: .env
    depends_on: [db, redis]

volumes:
  postgres_data:
