# Generated by Django 4.2.28 on 2026-03-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(default='Ghana', max_length=100)),
                ('profile_photo_url', models.URLField(blank=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('recipient_code', models.CharField(blank=True, max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
                ('welcome_bonus_claimed', models.BooleanField(default=False)),
                ('surveys_completed', models.JSONField(default=list)),
                ('offers_claimed', models.JSONField(default=list)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
