# Generated by Django 4.2.28 on 2026-03-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_photo_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
