# Generated by Django 4.2.28 on 2026-03-02 22:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=128)),
                ('amount_ghs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('points_converted', models.PositiveIntegerField()),
                ('recipient_code', models.CharField(max_length=100)),
                ('transfer_reference', models.CharField(max_length=200, unique=True)),
                ('transfer_code', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'withdrawals',
            },
        ),
    ]
