# Generated by Django 4.2.28 on 2026-03-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['user_id', 'status'], name='withdrawals_user_id_38a9fa_idx'),
        ),
    ]
