# Generated by Django 4.2.28 on 2026-03-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('points', models.PositiveIntegerField(default=0)),
                ('response_count', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'surveys',
            },
        ),
    ]
