# Generated by Django 4.2.28 on 2026-03-03 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_phase3_survey_question'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='question',
            new_name='questions_survey__8f7497_idx',
            old_name='questions_qu_survey__f6b26f_idx',
        ),
        migrations.RenameIndex(
            model_name='survey',
            new_name='surveys_is_dele_95ad15_idx',
            old_name='surveys_surv_is_dele_03c888_idx',
        ),
        migrations.RenameIndex(
            model_name='survey',
            new_name='surveys_is_dele_a2acc7_idx',
            old_name='surveys_surv_is_dele_6e16e8_idx',
        ),
    ]
