# Generated by Django 4.2.28 on 2026-03-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "surveys",
            "0003_rename_questions_qu_survey__f6b26f_idx_questions_survey__8f7497_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="question",
            name="questions_survey__8f7497_idx",
        ),
        migrations.RemoveIndex(
            model_name="survey",
            name="surveys_is_dele_95ad15_idx",
        ),
        migrations.RemoveIndex(
            model_name="survey",
            name="surveys_is_dele_a2acc7_idx",
        ),
        migrations.RemoveField(
            model_name="question",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="is_deleted",
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["survey", "position_index"], name="questions_survey__c59738_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="survey",
            index=models.Index(
                fields=["status", "-created_at"], name="surveys_status_6a3a63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="survey",
            index=models.Index(
                fields=["category", "-created_at"], name="surveys_categor_c1812d_idx"
            ),
        ),
    ]
