# Generated by Django 4.2.28 on 2026-03-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_survey_client_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyCategory',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'survey_categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('single_select', 'Single Select'), ('multi_select', 'Multi Select'), ('single_select_other', 'Single Select + Text'), ('multi_select_other', 'Multi Select + Text'), ('linear_scale', 'Linear Scale')], default='text', max_length=32),
        ),
    ]
