# Generated by Django 4.2.28 on 2026-03-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_alter_client_client_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="logo_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="client",
            name="website_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
